### ISSUE TITLE
Tidy up sending / processing multiple queries on start page

### ISSUE THREAD

**Issue by dave-mills** [dave-mills/proinpa#12]
Added second query as seperate call to getQueries() -> sql.query.  

We can keep adding queries as seperate calls, (and I've modified the dbLoaded to be a number that can count the number of queries loaded). 

But - it'd be far more elegant to just grab every single query from the masterQueries object and run them all in one go.

**Comment by chrismclarke** [comment]
What we should do is add a local database which is essentially a copy of the current masterQueries object but also include a `results:` key to return/cache queries. We would also need a way to know to rebuild when app is updated.

**Comment by chrismclarke** [comment]
Merged into #16
