### ISSUE TITLE
Abioticos images

### ISSUE THREAD

**Issue by chrismclarke** [dave-mills/proinpa#15]
Not really an issue to do with the app but was showing current build to rodrigo and antonio and they pointed out that the abioticos sequia image was wrong - when a new file is added to the main database it appends a number to the name on conflict. It would probably make more sense to rename the original file if possible and keep the new replacement. For now we can still change by hand

**Comment by dave-mills** [comment]
This will hopefully go away when we pull in the most recent upload files and database, as I assume they will have fixed it through the wordpress site.  Closing.
