### ISSUE TITLE
How to build query cache

### ISSUE THREAD

**Issue by chrismclarke** [dave-mills/proinpa#18]
Now app can import from cachedQueries.json file, however this needs to be populated. A couple options are:
1. Execute each query one-by-one within sqlite browser, export result as csv, copy/paste into mrdataconverter and finally copy/paste into json file
   (a little bit tedious but possibly easiest in first instance)
2. Write a short script in the app that will execute all known queries, save the results locally and then give option to download/export as single .json file which can then be added into the app
   (note., security restrictions prevent app from writing to local .json if executed in browser, but can create new file available for download. Can write to local device files via [file plugin](http://ionicframework.com/docs/v2/native/file/))
3. Implement local pouch/loki db, execute all queries on app first load and then store the results
   (could make for very slow first load, possibly could be combined with option 1 and/or 2)

I can see pros and cons of all these approaches, any other thoughts?

**Comment by dave-mills** [comment]
I'm happy to do option 1. 

Or, if option 2 would take less than 20 minutes, that would be a neat way of doing it.  When you say can create a new file for download, do you mean generate a link in the DOM that you press and get a download as per standard downloads? That's cool. 
1.  How much more optimised is it to have all the data in a pouch/loki compared with the SQLite? Sounds sort of like just transferring the data from one database to another, but it probably has benefits I don't know about.

**Comment by chrismclarke** [comment]
I think this discussion has mostly merged into #10 
I'm going to shelve auto-gen json data for now as there's not many queries to run and lots more stuff to figure out first
