### ISSUE TITLE
First Part, nearly there - but what to do with Varieties? 

### ISSUE THREAD

**Issue by dave-mills** [dave-mills/proinpa#23]
### Good news everyone!

We now have the following pathways working: 

Stage -> Risk (Abiotic, Disease or Pest) -> Possibilities -> Inputs -> Vendors
Stage -> Possibilities -> Inputs -> Vendors

---
### What to do with Varieties?

I'm not sure that it makes sense to include 'varieties' in this part, as they're not actually linked to anything except Vendors. 

Instead, how about we use Varieties as an excuse to start the 'catalogue(s)' section:
- add a menu at the start (or as a sidebar? Not sure the best way to do it), with the options:
  - View Information by Stage;
  - View Catalogue(s):

For now, it can just be a 'varieties' catalogue.  Later, we can expand it to include All The Things(tm)

**Comment by chrismclarke** [comment]
First of all, v. nice markup :+1: 
Second, I agree and imagine at some stage it makes sense to have catalogue pages for all areas of data to make it fast to find specific pests, vendors, varieties, diseases etc. I would suggest an initial page along the lines of
- Info by stage
- Catalogues
- Vendors

And then also sidebar menus on other pages to give quick access to these areas/views

**Comment by chrismclarke** [comment]
Gone for catalogue pages, can revisit later if feedback suggests alternate pathways needed
