### ISSUE TITLE
Update .db file with real one on Monday morning before demo

### ISSUE THREAD

**Issue by dave-mills** [dave-mills/proinpa#25]
When building, I found that there were no inputs associated with ANY possibilities.  Hopefully these links will be added at some point (if they're actually needed)

So, for testing, I linked one input to every activity (which is why the .db file was updated). 

This issue isn't intended for anything other than to note this, and remind us to update the .db (and the cached json, or is that automatically updated?)  before the demo.

**Comment by chrismclarke** [comment]
No json isn't automatically updated, I need to run all the queries in the db and copy/paste outputs. Just let me know what queries will have changed
