### ISSUE TITLE
Skipping pages

### ISSUE THREAD

**Issue by dave-mills** [dave-mills/proinpa#27]
Sometimes, there is only one item in a filtered list.  Do you think it makes sense to skip the list page and go straight to the details? 

My feeling is that showing a page with just a one-item list is pretty bare. (basically a waste of a page).  
_but_
I am also concerned that skipping straight to full details might be confusing if users are expecting to see a list of items? 

I basically want to know if you think either (or both) of these feelings/concerns are worth thinking about, before thinking more carefully about how to solve it.

**Comment by chrismclarke** [comment]
My feeling is that's not a problem for us. If there doesn't appear to be much data then the impetus is on the likes of proinpa to either a) generate more or b) live with it. I don't think we need to unnecessarily complicate our structures unless specifically asked to do so. I think here consistency is key and so am closing this discussion for the time being.
