### ISSUE TITLE
Catalogue list pages - same as the filtered list pages but without the filters?

### ISSUE THREAD

**Issue by dave-mills** [dave-mills/proinpa#35]
Thinking it might be good to use the pages we already have for the catalogue list? They're (probably) the same, just without a filter.  

I'm guessing this could be done by not passing a filter item / id in the nav.push(), then setting up the page to not require a filter?

**Comment by chrismclarke** [comment]
I'm all in favour of using as few templates as possible. Remember that ng-if statements can be used to show/hide minor changes and yes passing details through nav should work well. I'm planning similar for the abiotics/plagas/enfermedes pages

**Comment by dave-mills** [comment]
Sounds and looks good.  I see what you've done with the information-overview and instance-details pages (nice tabs btw).  I'll look at how I can link the catalogue pages to it.

**Comment by chrismclarke** [comment]
Implemented as far as needed for now, closing
