### ISSUE TITLE
Integrate inputs into management possibilities, possibly add ability to 'favourite'

### ISSUE THREAD

**Issue by chrismclarke** [dave-mills/proinpa#37]
Need to run sql query on management popup load and update inputs on same page to avoid additional navigation (often to empty pages). Would also be nice if we can 'favourite' inputs, although this will most likely involve adding a local cache/db to remember after app close.

**Comment by dave-mills** [comment]
Favouriting inputs, I suggest, can be a 'would like to see' addition.  The other bit - showing inputs (or lack thereof) for the management possibilities, is more important. 

I'll take your 'number of results' snippet and work it into the inputs tab.  Given the lack of data fields for the management possibilities (name, short description, image(s)), I'll play around with putting the actual list of inputs into the same page as the management details, so you can skip the 'inputs-list' page when navigating.

**Comment by chrismclarke** [comment]
As there currently isn't any input-possibility link data (at least in current json unless this is a mistake) I've simply put in a blank placeholder and will write a proper function when we have data to test with. Removing milestone

**Comment by chrismclarke** [comment]
Inputs now linked to management possibilties, closing for now and can reopen later if wanting to favourite.
