### ISSUE TITLE
Readme file update

### ISSUE THREAD

**Issue by chrismclarke** [dave-mills/proinpa#5]
Would be good to have some basic info in the readme including instructions how to download, serve and build (even if just links to ionic instruction pages). 

Later it should possibly stand as some mini-guide for the tecchie inclined to extend the project.

**Comment by dave-mills** [comment]
Have added a link to the ionic installation page and some basic answers to 'who' and 'what'. (why and how can come later...)

Closing this for now, mainly as I want to tidy up these issues in advance of the COP meeting. Feel free to re-open if you want to encourage us to write a more detailed readme!
