### ISSUE TITLE
Seperate out query set from main code

### ISSUE THREAD

**Issue by dave-mills** [dave-mills/proinpa#6]
I think it'd be useful to make a separate place (file, class, whatever the term is) to house all the queries.

**Comment by chrismclarke** [comment]
Agreed. a couple ways to do this, we already have the sql service provider which is a natural place, easiest option is to just create a variable at the end of the file (e.g. 
`var queriesMasterlist={
  name1: queryText
  name2: queryText2
}`
Other options would include have a seperate queries.json file that is placed in the www folder and imported in by the service (possibly better practice but adds an extra layer of complication as the file call is asynchronous using http.get request and you'll need to ensure it is complete before other things are done with the data)
