### ISSUE TITLE
Links from stage details to next page...

### ISSUE THREAD

**Issue by dave-mills** [dave-mills/proinpa#9]
Create buttons in stage detail view for the following items: 
- management possibilities
- abiotic risks
- diseases
- pests

Button is disabled (and visually different - greyed out?) if there are none of that item associated with the stage.  (i.e. query comes back with 0 results).

**Comment by dave-mills** [comment]
Buttons are in place.  The trick is to know whether there's anything behind the button...

**Comment by chrismclarke** [comment]
I've added a bit more styling to the buttons. I had wanted to run everything through an *ngFor loop and just define the template once but annoyingly navPush functions won't accept variables and I couldn't find a way around. Agreed on greying out, will look into it once I've got my head around the queries a bit more

**Comment by chrismclarke** [comment]
Merging into [https://github.com/dave-mills/proinpa/issues/10](url) as filtering will be dependent on queries
